name: Reusable Build Workflow

on:
  workflow_call:


jobs:
  example-job:
  runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
    	python-version: '3.10'

    - name: Install LSL-PyOptimizer
      run: bash ./scripts/install.sh

    - name: Build the project
      run: bash ./scripts/build.sh

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: text_board
        path: ./dist/text_board.min.lsl
