name: Build Project

on:
  workflow_dispatch:  # Permet de déclencher manuellement le workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install LSL-PyOptimizer
        run: bash ./scripts/install.sh

      - name: llvm (clang-cpp)
        run: | 
          sudo apt update
          sudo apt install -y clang llvm

      - name: Build the project
        run: bash ./scripts/build.sh
