name: Build Project

on:
  workflow_dispatch:  # Permet de déclencher manuellement le workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install LSL-PyOptimizer
        run: |
          python -m pip install --upgrade pip
          pip install LSL-PyOptimizer

      - name: llvm (clang-cpp)
        run: apt-get install llvm

      - name: Build the project
        run: ./scripts/build.sh
