name: Validate code

on:
  workflow_dispatch:

  push:
    branches:
      - develop

  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable/build.yml
	